#!/bin/bash
# author: Mike Rodarte
# accepts single command line argument of all
# example usage: ./get-ip

ifconfig | grep "inet addr" | awk -F: '{ print $2 }' | awk '{ print $1 }' 

# get return code from command
rc=$?
# if command failed, do it the old fashioned way
if [ "${rc}" -gt 0 ]; then
  file="ipaddr"
  touch ${file}
  ip addr > ${file}
  i=0
  found=false
  ips=()
  while read line
  do
    if [[ "$i" -eq "2" ]]; then
        # http://stackoverflow.com/questions/13373249/extract-substring-using-regexp-in-plain-bash
      ip=$([[ "$line" =~ ([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}) ]] && echo ${BASH_REMATCH[1]})
      ips+=($ip)
    fi

    if echo "$line" | grep -q "BROADCAST"; then
      found=true
      i=0
    fi

    if $found; then
      i=$(($i + 1))
    fi
  done < $file

  if [[ "$1" = "all" ]]; then
    for var in "${ips[@]}"
    do
      echo "${var}"
    done
  else
    echo "${ips[0]}"
  fi

  rm -f $file
fi
